services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      target: frontend-dev

    volumes:
      - ./frontend:/app
      - /app/node_modules

    ports:
      - 5173:5173

  backend:
    build:
      context: .
      dockerfile: Dockerfile
      target: backend-dev

    volumes:
      - ./backend:/app
      - /app/.venv

    ports:
      - 8000:8000
